package main

import (
	//"encoding/json"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

type AutoGenerated struct {
	Count          int    `json:"Count"`
	Message        string `json:"Message"`
	SearchCriteria any    `json:"SearchCriteria"`
	Results        []struct {
		Country       string `json:"Country"`
		MfrCommonName string `json:"Mfr_CommonName"`
		MfrID         int    `json:"Mfr_ID"`
		MfrName       string `json:"Mfr_Name"`
		VehicleTypes  []struct {
			IsPrimary bool   `json:"IsPrimary"`
			Name      string `json:"Name"`
		} `json:"VehicleTypes"`
	} `json:"Results"`
}

func main() {
	data, err := http.Get("https://vpic.nhtsa.dot.gov/api/vehicles/getallmanufacturers?format=json")
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(data.Body)
	}
	body, err := io.ReadAll(data.Body)
	if err == nil {
		//fmt.Println(string(body))//--> Yaha pe bas string(body) ye likhna tha phir aage steps dekhta bc string ko json me convert krta
	}
	var dat AutoGenerated
	errs := json.Unmarshal(body, &dat)
	if errs != nil {
		fmt.Println(errs)
	}
	fmt.Print(dat.Results, errs)

	for _, contry := range dat.Results {
		fmt.Println(contry.Country)
	}
}
